# ASG Airlines - Data Profiling
## 1. Load Source Data

In [5]:
import pandas as pd

file_path = "../data/raw/UseCase - Airlines.xlsx"

excel_file = pd.ExcelFile(file_path)

print(excel_file.sheet_names)

['flights', 'payments', 'bookings', 'passengers']

In [6]:
flights = pd.read_excel(file_path, sheet_name="flights")
bookings = pd.read_excel(file_path, sheet_name="bookings")
passengers = pd.read_excel(file_path, sheet_name="passengers")
payments = pd.read_excel(file_path, sheet_name="payments")

print("Flights:", flights.shape)
print("Bookings:", bookings.shape)
print("Passengers:", passengers.shape)
print("Payments:", payments.shape)

Flights: (1020, 7)
Bookings: (1000, 9)
Passengers: (1039, 9)
Payments: (1000, 4)

In [7]:
print("FLIGHTS")
display(flights.head())

print("\nBOOKINGS")
display(bookings.head())

print("\nPASSENGERS")
display(passengers.head())

print("\nPAYMENTS")
display(payments.head())

FLIGHTS

,flight_id,airline,source,destination,departure_time,arrival_time,duration
0,SJ010,SpiceJet,CCU,MAA,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,02:54:00
1,AI155,Air India,BOM,CCU,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,01:48:00
2,UK094,Vistara,BOM,CCU,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,01:45:00
3,AI245,Air India,BOM,CCU,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,02:36:00
4,AI192,Air India,MAA,BOM,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,04:59:00

BOOKINGS

,booking_id,passenger_id,flight_id,booking_date,status,passport_number,seat_number,emergency_contact_name,emergency_contact_phone
0,B1000,P1591,AI192,2025-06-14 11:37:36.951,CANCELLED,P1945887,3D,Isaac Bakshi,+91-6478475128
1,B1001,P1803,6F026,2025-11-02 11:37:36.951,CANCELLED,L3482012,18A,Anvi Konda,+91-6647078662
2,B1002,P1083,SJ010,2025-08-25 11:37:36.951,CANCELLED,G8507659,30C,Udant Dewan,+91-8405938220
3,B1003,P1364,AI069,2025-12-30 11:37:36.951,CONFIRMED,M0891776,33A,Harsh Chahal,+91-6264636839
4,B1004,P1885,UK003,2025-10-02 11:37:36.951,PENDING,N5742231,25C,Pahal Balay,+91-9336478266

PASSENGERS

,passenger_id,first_name,last_name,age,gender,email,phone,aadhaar_id,date_of_birth
0,P1000,Vivaan,Chatterjee,52,F,vivaan.chatterjee@gmail.com,+91-6896233790,433218196001,1974-04-08
1,P1001,Krishna,Reddy,15,M,krishna.reddy@hotmail.com,+91-6702632297,386379402654,2011-03-07
2,P1002,Myra,Naidu,72,M,myra.naidu@outlook.com,+91-6199585092,615594078161,1954-09-10
3,P1003,Myra,Mishra,61,F,myra.mishra@hotmail.com,+91-8719927151,310341316475,1965-03-12
4,P1004,Saanvi,Banerjee,21,M,saanvi.banerjee@outlook.com,+91-7819595113,419283276483,2005-11-11

PAYMENTS

  payment_id booking_id    amount payment_method
0    PAY1000      B1116   9883.49     NETBANKING
1    PAY1001      B1738   8457.96     NETBANKING
2    PAY1002      B1873   6495.37            UPI
3    PAY1003      B1914   5079.38     NETBANKING
4    PAY1004      B1967  12518.31           CARD

In [8]:
print("FLIGHTS - Missing Values")
print(flights.isnull().sum())

print("\nBOOKINGS - Missing Values")
print(bookings.isnull().sum())

print("\nPASSENGERS - Missing Values")
print(passengers.isnull().sum())

print("\nPAYMENTS - Missing Values")
print(payments.isnull().sum())

FLIGHTS - Missing Values
flight_id          0
airline           41
source             0
destination        0
departure_time     0
arrival_time       0
duration           0
dtype: int64

BOOKINGS - Missing Values
booking_id                  0
passenger_id                0
flight_id                   0
booking_date                0
status                     45
passport_number             0
seat_number                 0
emergency_contact_name      0
emergency_contact_phone     0
dtype: int64

PASSENGERS - Missing Values
passenger_id      0
first_name        0
last_name        10
age               0
gender            0
email             0
phone             0
aadhaar_id        0
date_of_birth     0
dtype: int64

PAYMENTS - Missing Values
payment_id         0
booking_id         0
amount            48
payment_method     0
dtype: int64

In [9]:
datasets = {
    "Flights": flights,
    "Bookings": bookings,
    "Passengers": passengers,
    "Payments": payments
}

for name, df in datasets.items():
    print(f"\n{name}")
    missing = df.isnull().sum()
    print(missing[missing > 0])

Flights
airline    41
dtype: int64

Bookings
status    45
dtype: int64

Passengers
last_name    10
dtype: int64

Payments
amount    48
dtype: int64

In [10]:
for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

Flights: 15 duplicate rows
Bookings: 0 duplicate rows
Passengers: 0 duplicate rows
Payments: 0 duplicate rows

In [11]:
print("Total flight records:", len(flights))
print("Unique flight IDs:", flights["flight_id"].nunique())
print("Duplicate flight IDs:", flights["flight_id"].duplicated().sum())

Total flight records: 1020
Unique flight IDs: 1004
Duplicate flight IDs: 16

In [12]:
duplicate_flight_ids = flights[
    flights["flight_id"].duplicated(keep=False)
].sort_values("flight_id")

display(duplicate_flight_ids)

,flight_id,airline,source,destination,departure_time,arrival_time,duration
253,6F250,UNKNOWN,DEL,BLR,2026-04-20 03:26:41.701,2026-04-20 07:30:41.701,04:04:00
270,6F250,UNKNOWN,CCU,BLR,2026-04-20 02:23:41.702,2026-04-20 02:56:41.702,00:33:00
550,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
549,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
141,AI031,Air India,DEL,MAA,2026-04-20 13:05:41.701,2026-04-20 16:11:41.701,03:06:00
142,AI031,Air India,DEL,MAA,2026-04-20 13:05:41.701,2026-04-20 16:11:41.701,03:06:00
599,AI043,Air India,CCU,DEL,2026-04-19 00:28:41.701,2026-04-19 04:37:41.701,04:09:00
598,AI043,Air India,CCU,DEL,2026-04-19 00:28:41.701,2026-04-19 04:37:41.701,04:09:00
603,AI070,Air India,CCU,DEL,2026-04-19 00:05:41.702,2026-04-19 01:44:41.702,01:39:00
602,AI070,Air India,CCU,DEL,2026-04-19 00:05:41.702,2026-04-19 01:44:41.702,01:39:00
83,AI242,UNKNOWN,BLR,CCU,2026-04-20 16:41:41.704,2026-04-20 17:43:41.704,01:02:00
84,AI242,UNKNOWN,BLR,CCU,2026-04-20 16:41:41.704,2026-04-20 17:43:41.704,01:02:00
939,SJ037,SpiceJet,BLR,BOM,2026-04-17 19:14:41.701,2026-04-17 22:31:41.701,03:17:00
940,SJ037,SpiceJet,BLR,BOM,2026-04-17 19:14:41.701,2026-04-17 22:31:41.701,03:17:00
588,SJ118,SpiceJet,DEL,BOM,2026-04-19 01:08:41.702,2026-04-19 02:33:41.702,01:25:00
589,SJ118,SpiceJet,DEL,BOM,2026-04-19 01:08:41.702,2026-04-19 02:33:41.702,01:25:00
106,SJ142,SpiceJet,CCU,BOM,2026-04-20 15:14:41.702,2026-04-20 16:56:41.702,01:42:00
105,SJ142,SpiceJet,CCU,BOM,2026-04-20 15:14:41.702,2026-04-20 16:56:41.702,01:42:00
310,SJ146,SpiceJet,HYD,BLR,2026-04-19 22:37:41.702,2026-04-20 00:33:41.702,01:56:00
309,SJ146,SpiceJet,HYD,BLR,2026-04-19 22:37:41.702,2026-04-20 00:33:41.702,01:56:00
605,UK013,Vistara,BOM,MAA,2026-04-18 23:52:41.701,2026-04-19 02:52:41.701,03:00:00
606,UK013,Vistara,BOM,MAA,2026-04-18 23:52:41.701,2026-04-19 02:52:41.701,03:00:00
935,UK049,Vistara,HYD,BOM,2026-04-17 19:47:41.701,2026-04-17 20:32:41.701,00:45:00
936,UK049,Vistara,HYD,BOM,2026-04-17 19:47:41.701,2026-04-17 20:32:41.701,00:45:00
759,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
758,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
812,UK160,Vistara,BLR,BOM,2026-04-18 06:42:41.703,2026-04-18 10:58:41.703,04:16:00
813,UK160,Vistara,BLR,BOM,2026-04-18 06:42:41.703,2026-04-18 10:58:41.703,04:16:00
503,UK163,Vistara,DEL,HYD,2026-04-19 07:22:41.703,2026-04-19 09:04:41.703,01:42:00
502,UK163,Vistara,DEL,HYD,2026-04-19 07:22:41.703,2026-04-19 09:04:41.703,01:42:00
914,UK180,Vistara,CCU,MAA,2026-04-17 21:18:41.703,2026-04-17 23:29:41.703,02:11:00
915,UK180,Vistara,CCU,MAA,2026-04-17 21:18:41.703,2026-04-17 23:29:41.703,02:11:00

In [13]:
print(flights["flight_id"].unique())

<StringArray>
['SJ010', 'AI155', 'UK094', 'AI245', 'AI192', 'SJ158', '6F196', 'AI080',
 '6F025', '6F251',
 ...
 'AI052', 'SJ177', '6F215', 'AI223', 'SJ069', '6F198', 'AI093', 'UK062',
 '6F057', 'UK064']
Length: 1004, dtype: str

In [14]:
flight_id_lengths = flights["flight_id"].astype(str).str.len()

print(flight_id_lengths.value_counts().sort_index())

flight_id
5    1020
Name: count, dtype: int64

In [15]:
pattern = r"^[A-Za-z0-9]{2}\d{3}$"

invalid_ids = flights[
    ~flights["flight_id"].astype(str).str.match(pattern)
]

print("Invalid flight IDs:", len(invalid_ids))

display(invalid_ids)

Invalid flight IDs: 0

Empty DataFrame
Columns: [flight_id, airline, source, destination, departure_time, arrival_time, duration]
Index: []

In [16]:
print(flights[["departure_time", "arrival_time", "duration"]].dtypes)

departure_time    datetime64[us]
arrival_time      datetime64[us]
duration                  object
dtype: object

In [17]:
flights[["flight_id", "departure_time", "arrival_time", "duration"]].head(10)

  flight_id          departure_time            arrival_time  duration
0     SJ010 2026-04-20 23:38:41.701 2026-04-21 02:32:41.701  02:54:00
1     AI155 2026-04-20 23:35:41.703 2026-04-21 01:23:41.703  01:48:00
2     UK094 2026-04-20 23:26:41.702 2026-04-21 01:11:41.702  01:45:00
3     AI245 2026-04-20 23:07:41.704 2026-04-21 01:43:41.704  02:36:00
4     AI192 2026-04-20 23:05:41.703 2026-04-21 04:04:41.703  04:59:00
5     SJ158 2026-04-20 23:05:41.703 2026-04-21 01:24:41.703  02:19:00
6     6F196 2026-04-20 23:04:41.703 2026-04-21 00:47:41.703  01:43:00
7     AI080 2026-04-20 23:03:41.702 2026-04-21 00:35:41.702  01:32:00
8     6F025 2026-04-20 23:02:41.701 2026-04-20 23:57:41.701  00:55:00
9     6F251 2026-04-20 22:56:41.703 2026-04-20 23:37:41.703  00:41:00

In [18]:
flights["calculated_duration"] = (
    flights["arrival_time"] - flights["departure_time"]
)

display(
    flights[
        ["flight_id", "departure_time", "arrival_time",
         "duration", "calculated_duration"]
    ].head(10)
)

,flight_id,departure_time,arrival_time,duration,calculated_duration
0,SJ010,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,02:54:00,0 days 02:54:00
1,AI155,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,01:48:00,0 days 01:48:00
2,UK094,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,01:45:00,0 days 01:45:00
3,AI245,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,02:36:00,0 days 02:36:00
4,AI192,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,04:59:00,0 days 04:59:00
5,SJ158,2026-04-20 23:05:41.703,2026-04-21 01:24:41.703,02:19:00,0 days 02:19:00
6,6F196,2026-04-20 23:04:41.703,2026-04-21 00:47:41.703,01:43:00,0 days 01:43:00
7,AI080,2026-04-20 23:03:41.702,2026-04-21 00:35:41.702,01:32:00,0 days 01:32:00
8,6F025,2026-04-20 23:02:41.701,2026-04-20 23:57:41.701,00:55:00,0 days 00:55:00
9,6F251,2026-04-20 22:56:41.703,2026-04-20 23:37:41.703,00:41:00,0 days 00:41:00

In [22]:
flights["duration_timedelta"] = pd.to_timedelta(
    flights["duration"].astype(str)
)

print(flights[["duration", "duration_timedelta"]].head())

ValueError: only leading negative signs are allowed

In [23]:
bad_duration = pd.to_timedelta(
    flights["duration"].astype(str),
    errors="coerce"
)

print("Invalid duration values:", bad_duration.isna().sum())

print(
    flights.loc[
        bad_duration.isna(),
        ["duration"]
    ].head(20)
)

Invalid duration values: 1
                duration
355  1899-12-29 05:00:00

In [24]:
print(
    flights.loc[
        355,
        ["flight_id", "departure_time", "arrival_time", "duration"]
    ]
)

flight_id                       SJ192
departure_time    2026-04-19 18:45:42
arrival_time      2026-04-18 23:45:42
duration          1899-12-29 05:00:00
Name: 355, dtype: object

In [25]:
time_issue = flights[flights["arrival_time"] < flights["departure_time"]]

print("Flights with arrival before departure:", len(time_issue))

print(
    time_issue[
        ["flight_id", "departure_time", "arrival_time", "duration"]
    ]
)

Flights with arrival before departure: 1
    flight_id      departure_time        arrival_time             duration
355     SJ192 2026-04-19 18:45:42 2026-04-18 23:45:42  1899-12-29 05:00:00

In [26]:
print(
    flights.loc[
        355,
        ["departure_time", "arrival_time"]
    ]
)

print(
    "Difference:",
    flights.loc[355, "arrival_time"] - flights.loc[355, "departure_time"]
)

departure_time   2026-04-19 18:45:42
arrival_time     2026-04-18 23:45:42
Name: 355, dtype: datetime64[us]
Difference: -1 days +05:00:00

In [27]:
print(
    flights[
        (flights["source"] == flights.loc[355, "source"]) &
        (flights["destination"] == flights.loc[355, "destination"])
    ][
        ["flight_id", "source", "destination",
         "departure_time", "arrival_time", "duration"]
    ].head(20)
)

    flight_id source destination          departure_time  \
36      SJ047    HYD         BOM 2026-04-20 20:44:41.701
37      AI179    HYD         BOM 2026-04-20 20:41:41.703
90      UK077    HYD         BOM 2026-04-20 16:22:41.702
161     6F074    HYD         BOM 2026-04-20 11:09:41.702
191     SJ226    HYD         BOM 2026-04-20 08:47:41.704
343     6F003    HYD         BOM 2026-04-19 20:06:41.700
344     6F249    HYD         BOM 2026-04-19 20:06:41.700
355     SJ192    HYD         BOM 2026-04-19 18:45:42.000
365     6F127    HYD         BOM 2026-04-19 18:27:41.702
456     6F001    HYD         BOM 2026-04-19 11:33:41.700
458     SJ199    HYD         BOM 2026-04-19 11:29:41.703
469     6F220    HYD         BOM 2026-04-19 10:27:41.704
497     AI028    HYD         BOM 2026-04-19 07:53:41.701
541     UK201    HYD         BOM 2026-04-19 04:29:41.703
591     UK097    HYD         BOM 2026-04-19 00:49:41.702
597     AI134    HYD         BOM 2026-04-19 00:28:41.702
625     6F016    HYD         BOM 2026-04-18 22:18:41.701
636     UK035    HYD         BOM 2026-04-18 21:08:41.701
746     6F144    HYD         BOM 2026-04-18 11:56:41.702
809     UK125    HYD         BOM 2026-04-18 06:58:41.702

               arrival_time             duration
36  2026-04-20 21:21:41.701             00:37:00
37  2026-04-21 01:19:41.703             04:38:00
90  2026-04-20 18:00:41.702             01:38:00
161 2026-04-20 14:29:41.702             03:20:00
191 2026-04-20 12:54:41.704             04:07:00
343 2026-04-19 23:13:41.700             03:07:00
344 2026-04-19 23:13:41.700             03:07:00
355 2026-04-18 23:45:42.000  1899-12-29 05:00:00
365 2026-04-19 22:28:41.702             04:01:00
456 2026-04-19 13:08:41.700             01:35:00
458 2026-04-19 13:59:41.703             02:30:00
469 2026-04-19 11:25:41.704             00:58:00
497 2026-04-19 08:35:41.701             00:42:00
541 2026-04-19 06:42:41.703             02:13:00
591 2026-04-19 05:00:41.702             04:11:00
597 2026-04-19 04:23:41.702             03:55:00
625 2026-04-18 22:54:41.701             00:36:00
636 2026-04-18 22:24:41.701             01:16:00
746 2026-04-18 15:11:41.702             03:15:00
809 2026-04-18 11:44:41.702             04:46:00

In [28]:
flights["duration_timedelta"] = pd.to_timedelta(
    flights["duration"].astype(str),
    errors="coerce"
)

print(flights["duration_timedelta"].isna().sum())

1

In [29]:
flights.loc[355, "duration_timedelta"] = pd.Timedelta(hours=5)

print(
    flights.loc[
        355,
        ["flight_id", "duration", "duration_timedelta"]
    ]
)

flight_id                           SJ192
duration              1899-12-29 05:00:00
duration_timedelta        0 days 05:00:00
Name: 355, dtype: object

In [30]:
flights["calculated_duration"] = (
    flights["arrival_time"] - flights["departure_time"]
)

mismatch = flights[
    flights["duration_timedelta"] != flights["calculated_duration"]
]

print("Duration mismatches:", len(mismatch))

Duration mismatches: 1

In [31]:
print(
    mismatch[
        [
            "flight_id",
            "departure_time",
            "arrival_time",
            "duration_timedelta",
            "calculated_duration"
        ]
    ]
)

    flight_id      departure_time        arrival_time duration_timedelta  \
355     SJ192 2026-04-19 18:45:42 2026-04-18 23:45:42    0 days 05:00:00

    calculated_duration
355   -1 days +05:00:00

In [32]:
flights["time_anomaly"] = (
    flights["arrival_time"] < flights["departure_time"]
)

print(
    flights[flights["time_anomaly"]][
        ["flight_id", "departure_time", "arrival_time", "time_anomaly"]
    ]
)

    flight_id      departure_time        arrival_time  time_anomaly
355     SJ192 2026-04-19 18:45:42 2026-04-18 23:45:42          True

In [33]:
invalid_booking_flights = bookings[
    ~bookings["flight_id"].isin(flights["flight_id"])
]

print("Bookings with invalid flight IDs:", len(invalid_booking_flights))

Bookings with invalid flight IDs: 0

In [34]:
invalid_booking_passengers = bookings[
    ~bookings["passenger_id"].isin(passengers["passenger_id"])
]

print(
    "Bookings with invalid passenger IDs:",
    len(invalid_booking_passengers)
)

Bookings with invalid passenger IDs: 0

In [35]:
invalid_payment_bookings = payments[
    ~payments["booking_id"].isin(bookings["booking_id"])
]

print(
    "Payments with invalid booking IDs:",
    len(invalid_payment_bookings)
)

Payments with invalid booking IDs: 0

In [36]:
print(flights["airline"].value_counts(dropna=False))

airline
IndiGo       249
SpiceJet     240
Air India    236
Vistara      223
NaN           41
UNKNOWN       31
Name: count, dtype: int64

In [37]:
print(flights["source"].value_counts(dropna=False))

source
BOM    207
HYD    180
CCU    174
DEL    163
MAA    157
BLR    139
Name: count, dtype: int64

In [38]:
print(flights["destination"].value_counts(dropna=False))

destination
DEL    200
CCU    188
BOM    174
BLR    165
MAA    151
HYD    142
Name: count, dtype: int64

In [39]:
print(bookings["status"].value_counts(dropna=False))

status
CONFIRMED    320
CANCELLED    314
PENDING      291
NaN           45
INVALID       30
Name: count, dtype: int64

In [40]:
print(
    bookings[bookings["status"] == "INVALID"][
        ["booking_id", "passenger_id", "flight_id", "status"]
    ].head(10)
)

    booking_id passenger_id flight_id   status
49       B1049        P1072     SJ153  INVALID
102      B1102        P1448     SJ196  INVALID
162      B1162        P1027     AI146  INVALID
198      B1198        P1913     SJ022  INVALID
208      B1208        P1284     SJ052  INVALID
268      B1268        P1657     AI102  INVALID
283      B1283        P1860     AI103  INVALID
286      B1286        P1753     6F010  INVALID
304      B1304        P1254     6F022  INVALID
337      B1337        P1028     6F246  INVALID

In [41]:
print(
    bookings[bookings["status"].isna()][
        ["booking_id", "passenger_id", "flight_id", "status"]
    ].head(10)
)

    booking_id passenger_id flight_id status
15       B1015        P1431     UK094    NaN
33       B1033        P1987     UK026    NaN
45       B1045        P1057     SJ214    NaN
97       B1097        P1959     6F017    NaN
98       B1098        P1491     6F245    NaN
214      B1214        P1187     UK194    NaN
223      B1223        P1755     6F056    NaN
237      B1237        P1754     AI047    NaN
238      B1238        P1296     SJ186    NaN
245      B1245        P1139     6F201    NaN

In [42]:
print(passengers["gender"].value_counts(dropna=False))

gender
M    545
F    494
Name: count, dtype: int64

In [43]:
print(passengers["age"].describe())

count    1039.000000
mean       43.304139
std        25.900616
min         1.000000
25%        20.000000
50%        43.000000
75%        64.000000
max        89.000000
Name: age, dtype: float64

In [44]:
print(payments["payment_method"].value_counts(dropna=False))

payment_method
UPI           358
CARD          329
NETBANKING    313
Name: count, dtype: int64

In [45]:
print(payments["amount"].describe())

count         952
unique        922
top       INVALID
freq           30
Name: amount, dtype: object

In [46]:
print(
    payments[payments["amount"] == "INVALID"][
        ["payment_id", "booking_id", "amount", "payment_method"]
    ].head(10)
)

    payment_id booking_id   amount payment_method
19     PAY1019      B1875  INVALID     NETBANKING
33     PAY1033      B1012  INVALID           CARD
77     PAY1077      B1501  INVALID            UPI
173    PAY1173      B1722  INVALID           CARD
213    PAY1213      B1725  INVALID     NETBANKING
244    PAY1244      B1844  INVALID           CARD
249    PAY1249      B1816  INVALID     NETBANKING
290    PAY1290      B1605  INVALID           CARD
323    PAY1323      B1314  INVALID     NETBANKING
408    PAY1408      B1146  INVALID            UPI

In [47]:
valid_amounts = payments[
    ~payments["amount"].isin(["INVALID"])
]["amount"]

print(valid_amounts.head(10))
print(valid_amounts.dtype)

0     9883.49
1     8457.96
2     6495.37
3     5079.38
4    12518.31
5     7319.71
6     8020.26
7      8291.6
8     7277.14
9     4585.24
Name: amount, dtype: object
object

In [48]:
payments["amount_numeric"] = pd.to_numeric(
    payments["amount"],
    errors="coerce"
)

print(payments[["amount", "amount_numeric"]].head(10))

     amount  amount_numeric
0   9883.49         9883.49
1   8457.96         8457.96
2   6495.37         6495.37
3   5079.38         5079.38
4  12518.31        12518.31
5   7319.71         7319.71
6   8020.26         8020.26
7    8291.6         8291.60
8   7277.14         7277.14
9   4585.24         4585.24

In [49]:
print(
    "Missing/invalid payment amounts:",
    payments["amount_numeric"].isna().sum()
)

Missing/invalid payment amounts: 78

In [50]:
print(payments["amount_numeric"].describe())

count      922.000000
mean      8009.916464
std       4022.055392
min       1002.590000
25%       4623.495000
50%       8027.125000
75%      11288.155000
max      14992.950000
Name: amount_numeric, dtype: float64

In [51]:
flights_clean = flights.drop_duplicates().copy()

print("Original rows:", len(flights))
print("Cleaned rows:", len(flights_clean))
print("Rows removed:", len(flights) - len(flights_clean))

Original rows: 1020
Cleaned rows: 1005
Rows removed: 15

In [52]:
duplicate_ids = flights_clean[
    flights_clean["flight_id"].duplicated(keep=False)
]

print("Rows with duplicate flight IDs:", len(duplicate_ids))

print(
    duplicate_ids["flight_id"]
    .value_counts()
)

Rows with duplicate flight IDs: 2
flight_id
6F250    2
Name: count, dtype: int64

In [53]:
print(
    flights_clean[
        flights_clean["flight_id"] == "6F250"
    ]
)

    flight_id  airline source destination          departure_time  \
253     6F250  UNKNOWN    DEL         BLR 2026-04-20 03:26:41.701
270     6F250  UNKNOWN    CCU         BLR 2026-04-20 02:23:41.702

               arrival_time  duration calculated_duration duration_timedelta  \
253 2026-04-20 07:30:41.701  04:04:00     0 days 04:04:00    0 days 04:04:00
270 2026-04-20 02:56:41.702  00:33:00     0 days 00:33:00    0 days 00:33:00

     time_anomaly
253         False
270         False

In [54]:
flights_clean["duplicate_flight_id"] = (
    flights_clean["flight_id"].duplicated(keep=False)
)

print(
    flights_clean[flights_clean["duplicate_flight_id"]][
        ["flight_id", "source", "destination", "duplicate_flight_id"]
    ]
)

    flight_id source destination  duplicate_flight_id
253     6F250    DEL         BLR                 True
270     6F250    CCU         BLR                 True

In [55]:
print(
    flights_clean[flights_clean["airline"].isna()][
        ["flight_id", "airline", "source", "destination", "duration"]
    ].head(10)
)

    flight_id airline source destination  duration
57      UK209     NaN    MAA         BLR  02:45:00
63      6F270     NaN    HYD         MAA  00:48:00
89      UK224     NaN    CCU         MAA  03:59:00
118     6F261     NaN    CCU         DEL  02:58:00
120     6F254     NaN    MAA         BLR  03:35:00
124     6F259     NaN    BOM         DEL  01:11:00
133     UK141     NaN    HYD         MAA  02:21:00
150     6F255     NaN    DEL         BOM  03:34:00
218     AI047     NaN    CCU         MAA  00:47:00
222     AI128     NaN    BOM         CCU  03:56:00

In [56]:
flights_clean["airline_missing"] = flights_clean["airline"].isna()

print(
    "Missing airline records:",
    flights_clean["airline_missing"].sum()
)

Missing airline records: 39

In [57]:
print(
    "UNKNOWN airline records:",
    (flights_clean["airline"] == "UNKNOWN").sum()
)

UNKNOWN airline records: 30

In [58]:
flights_clean["airline_standard"] = flights_clean["airline"].fillna("Unknown")

print(
    flights_clean["airline_standard"].value_counts()
)

airline_standard
IndiGo       249
SpiceJet     236
Air India    233
Vistara      218
Unknown       39
UNKNOWN       30
Name: count, dtype: int64

In [59]:
flights_clean["airline_standard"] = (
    flights_clean["airline"]
    .fillna("Unknown")
    .replace("UNKNOWN", "Unknown")
)

print(
    flights_clean["airline_standard"].value_counts()
)

airline_standard
IndiGo       249
SpiceJet     236
Air India    233
Vistara      218
Unknown       69
Name: count, dtype: int64

In [60]:
bookings_clean = bookings.copy()

bookings_clean["status_standard"] = (
    bookings_clean["status"]
    .fillna("Unknown")
    .replace("INVALID", "Unknown")
)

print(
    bookings_clean["status_standard"].value_counts()
)

status_standard
CONFIRMED    320
CANCELLED    314
PENDING      291
Unknown       75
Name: count, dtype: int64

In [61]:
passengers_clean = passengers.copy()

passengers_clean["last_name_missing"] = (
    passengers_clean["last_name"].isna()
)

print(
    "Missing last names:",
    passengers_clean["last_name_missing"].sum()
)

Missing last names: 10

In [62]:
payments_clean = payments.copy()

payments_clean["amount_missing"] = (
    payments_clean["amount_numeric"].isna()
)

print(
    "Missing/invalid amounts:",
    payments_clean["amount_missing"].sum()
)

Missing/invalid amounts: 78

In [63]:
print(flights_clean.columns.tolist())

['flight_id', 'airline', 'source', 'destination', 'departure_time', 'arrival_time', 'duration', 'calculated_duration', 'duration_timedelta', 'time_anomaly', 'duplicate_flight_id', 'airline_missing', 'airline_standard']

In [64]:
flights_clean["duration_minutes"] = (
    flights_clean["duration_timedelta"].dt.total_seconds() / 60
)

print(
    flights_clean[
        ["flight_id", "duration_timedelta", "duration_minutes"]
    ].head(10)
)

  flight_id duration_timedelta  duration_minutes
0     SJ010    0 days 02:54:00             174.0
1     AI155    0 days 01:48:00             108.0
2     UK094    0 days 01:45:00             105.0
3     AI245    0 days 02:36:00             156.0
4     AI192    0 days 04:59:00             299.0
5     SJ158    0 days 02:19:00             139.0
6     6F196    0 days 01:43:00             103.0
7     AI080    0 days 01:32:00              92.0
8     6F025    0 days 00:55:00              55.0
9     6F251    0 days 00:41:00              41.0

In [65]:
print(
    "Missing duration values:",
    flights_clean["duration_minutes"].isna().sum()
)

Missing duration values: 0

In [66]:
flights_clean["overnight_flight"] = (
    flights_clean["arrival_time"].dt.date
    != flights_clean["departure_time"].dt.date
)

print(
    "Overnight flights:",
    flights_clean["overnight_flight"].sum()
)

Overnight flights: 123

In [67]:
print(
    flights_clean[
        flights_clean["overnight_flight"] &
        flights_clean["time_anomaly"]
    ][
        ["flight_id", "departure_time", "arrival_time"]
    ]
)

    flight_id      departure_time        arrival_time
355     SJ192 2026-04-19 18:45:42 2026-04-18 23:45:42

In [68]:
flights_clean["overnight_flight"] = (
    flights_clean["arrival_time"].dt.date
    > flights_clean["departure_time"].dt.date
)

print(
    "Overnight flights:",
    flights_clean["overnight_flight"].sum()
)

print(
    "Anomalous overnight flights:",
    flights_clean[
        flights_clean["time_anomaly"] &
        flights_clean["overnight_flight"]
    ].shape[0]
)

Overnight flights: 122
Anomalous overnight flights: 0

In [69]:
flights_clean["route"] = (
    flights_clean["source"] + " → " + flights_clean["destination"]
)

print(
    flights_clean[
        ["source", "destination", "route"]
    ].head(10)
)

  source destination      route
0    CCU         MAA  CCU → MAA
1    BOM         CCU  BOM → CCU
2    BOM         CCU  BOM → CCU
3    BOM         CCU  BOM → CCU
4    MAA         BOM  MAA → BOM
5    DEL         HYD  DEL → HYD
6    CCU         MAA  CCU → MAA
7    BOM         HYD  BOM → HYD
8    BLR         BOM  BLR → BOM
9    DEL         BLR  DEL → BLR

In [70]:
print(
    "Unique routes:",
    flights_clean["route"].nunique()
)

print(
    flights_clean["route"].value_counts().head(10)
)

Unique routes: 30
route
BOM → CCU    90
CCU → DEL    72
MAA → BLR    65
BLR → BOM    60
HYD → MAA    57
DEL → HYD    54
HYD → DEL    42
BOM → DEL    39
CCU → BOM    33
DEL → BLR    29
Name: count, dtype: int64

In [71]:
average_duration = flights_clean["duration_minutes"].mean()

print(
    "Average Flight Duration:",
    round(average_duration, 2),
    "minutes"
)

Average Flight Duration: 164.62 minutes

In [72]:
avg_duration_airline = (
    flights_clean
    .groupby("airline_standard")["duration_minutes"]
    .mean()
    .round(2)
)

print(avg_duration_airline)

airline_standard
Air India    163.15
IndiGo       167.70
SpiceJet     164.19
Unknown      166.07
Vistara      162.68
Name: duration_minutes, dtype: float64

In [73]:
route_traffic = (
    flights_clean["route"]
    .value_counts()
    .reset_index()
)

route_traffic.columns = ["route", "flight_count"]

print(route_traffic.head(10))

       route  flight_count
0  BOM → CCU            90
1  CCU → DEL            72
2  MAA → BLR            65
3  BLR → BOM            60
4  HYD → MAA            57
5  DEL → HYD            54
6  HYD → DEL            42
7  BOM → DEL            39
8  CCU → BOM            33
9  DEL → BLR            29

In [74]:
airline_distribution = (
    flights_clean["airline_standard"]
    .value_counts()
    .reset_index()
)

airline_distribution.columns = ["airline", "flight_count"]

print(airline_distribution)

     airline  flight_count
0     IndiGo           249
1   SpiceJet           236
2  Air India           233
3    Vistara           218
4    Unknown            69

In [75]:
anomaly_count = flights_clean["time_anomaly"].sum()
anomaly_percentage = (
    anomaly_count / len(flights_clean) * 100
)

print("Time anomalies:", anomaly_count)
print("Anomaly percentage:", round(anomaly_percentage, 2), "%")

Time anomalies: 1
Anomaly percentage: 0.1 %

In [76]:
kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Flights",
        "Average Flight Duration (minutes)",
        "Overnight Flights",
        "Time Anomalies",
        "Unique Routes"
    ],
    "Value": [
        len(flights_clean),
        round(flights_clean["duration_minutes"].mean(), 2),
        flights_clean["overnight_flight"].sum(),
        flights_clean["time_anomaly"].sum(),
        flights_clean["route"].nunique()
    ]
})

print(kpi_summary)

                                 KPI    Value
0                      Total Flights  1005.00
1  Average Flight Duration (minutes)   164.62
2                  Overnight Flights   122.00
3                     Time Anomalies     1.00
4                      Unique Routes    30.00

In [77]:
print(
    flights_clean[
        [
            "flight_id",
            "airline_standard",
            "source",
            "destination",
            "route",
            "departure_time",
            "arrival_time",
            "duration_minutes",
            "overnight_flight",
            "time_anomaly",
            "duplicate_flight_id"
        ]
    ].head()
)

  flight_id airline_standard source destination      route  \
0     SJ010         SpiceJet    CCU         MAA  CCU → MAA
1     AI155        Air India    BOM         CCU  BOM → CCU
2     UK094          Vistara    BOM         CCU  BOM → CCU
3     AI245        Air India    BOM         CCU  BOM → CCU
4     AI192        Air India    MAA         BOM  MAA → BOM

           departure_time            arrival_time  duration_minutes  \
0 2026-04-20 23:38:41.701 2026-04-21 02:32:41.701             174.0
1 2026-04-20 23:35:41.703 2026-04-21 01:23:41.703             108.0
2 2026-04-20 23:26:41.702 2026-04-21 01:11:41.702             105.0
3 2026-04-20 23:07:41.704 2026-04-21 01:43:41.704             156.0
4 2026-04-20 23:05:41.703 2026-04-21 04:04:41.703             299.0

   overnight_flight  time_anomaly  duplicate_flight_id
0              True         False                False
1              True         False                False
2              True         False                False
3              True         False                False
4              True         False                False

In [78]:
flights_final = flights_clean[
    [
        "flight_id",
        "airline_standard",
        "source",
        "destination",
        "route",
        "departure_time",
        "arrival_time",
        "duration_minutes",
        "overnight_flight",
        "time_anomaly"
    ]
].copy()

print(flights_final.shape)
print(flights_final.head())

(1005, 10)
  flight_id airline_standard source destination      route  \
0     SJ010         SpiceJet    CCU         MAA  CCU → MAA
1     AI155        Air India    BOM         CCU  BOM → CCU
2     UK094          Vistara    BOM         CCU  BOM → CCU
3     AI245        Air India    BOM         CCU  BOM → CCU
4     AI192        Air India    MAA         BOM  MAA → BOM

           departure_time            arrival_time  duration_minutes  \
0 2026-04-20 23:38:41.701 2026-04-21 02:32:41.701             174.0
1 2026-04-20 23:35:41.703 2026-04-21 01:23:41.703             108.0
2 2026-04-20 23:26:41.702 2026-04-21 01:11:41.702             105.0
3 2026-04-20 23:07:41.704 2026-04-21 01:43:41.704             156.0
4 2026-04-20 23:05:41.703 2026-04-21 04:04:41.703             299.0

   overnight_flight  time_anomaly
0              True         False
1              True         False
2              True         False
3              True         False
4              True         False

In [79]:
bookings_clean = bookings.copy()

bookings_clean["status_standard"] = (
    bookings_clean["status"]
    .fillna("Unknown")
    .replace("INVALID", "Unknown")
)

print(bookings_clean["status_standard"].value_counts())

status_standard
CONFIRMED    320
CANCELLED    314
PENDING      291
Unknown       75
Name: count, dtype: int64

In [80]:
bookings_final = bookings_clean[
    [
        "booking_id",
        "passenger_id",
        "flight_id",
        "booking_date",
        "status_standard",
        "passport_number",
        "seat_number",
        "emergency_contact_name",
        "emergency_contact_phone"
    ]
].copy()

print(bookings_final.shape)
print(bookings_final.head())

(1000, 9)
  booking_id passenger_id flight_id            booking_date status_standard  \
0      B1000        P1591     AI192 2025-06-14 11:37:36.951       CANCELLED
1      B1001        P1803     6F026 2025-11-02 11:37:36.951       CANCELLED
2      B1002        P1083     SJ010 2025-08-25 11:37:36.951       CANCELLED
3      B1003        P1364     AI069 2025-12-30 11:37:36.951       CONFIRMED
4      B1004        P1885     UK003 2025-10-02 11:37:36.951         PENDING

  passport_number seat_number emergency_contact_name emergency_contact_phone
0        P1945887          3D           Isaac Bakshi          +91-6478475128
1        L3482012         18A             Anvi Konda          +91-6647078662
2        G8507659         30C            Udant Dewan          +91-8405938220
3        M0891776         33A           Harsh Chahal          +91-6264636839
4        N5742231         25C            Pahal Balay          +91-9336478266

In [81]:
bookings_analytics = bookings_final[
    [
        "booking_id",
        "passenger_id",
        "flight_id",
        "booking_date",
        "status_standard",
        "seat_number"
    ]
].copy()

print(bookings_analytics.shape)
print(bookings_analytics.head())

(1000, 6)
  booking_id passenger_id flight_id            booking_date status_standard  \
0      B1000        P1591     AI192 2025-06-14 11:37:36.951       CANCELLED
1      B1001        P1803     6F026 2025-11-02 11:37:36.951       CANCELLED
2      B1002        P1083     SJ010 2025-08-25 11:37:36.951       CANCELLED
3      B1003        P1364     AI069 2025-12-30 11:37:36.951       CONFIRMED
4      B1004        P1885     UK003 2025-10-02 11:37:36.951         PENDING

  seat_number
0          3D
1         18A
2         30C
3         33A
4         25C

In [82]:
passengers_clean = passengers.copy()

passengers_clean["last_name_missing"] = (
    passengers_clean["last_name"].isna()
)

print(
    "Missing last names:",
    passengers_clean["last_name_missing"].sum()
)

Missing last names: 10

In [83]:
passengers_analytics = passengers_clean[
    [
        "passenger_id",
        "first_name",
        "last_name",
        "age",
        "gender",
        "date_of_birth"
    ]
].copy()

print(passengers_analytics.shape)
print(passengers_analytics.head())

(1039, 6)
  passenger_id first_name   last_name  age gender date_of_birth
0        P1000     Vivaan  Chatterjee   52      F    1974-04-08
1        P1001    Krishna       Reddy   15      M    2011-03-07
2        P1002       Myra       Naidu   72      M    1954-09-10
3        P1003       Myra      Mishra   61      F    1965-03-12
4        P1004     Saanvi    Banerjee   21      M    2005-11-11

In [84]:
payments_clean = payments.copy()

payments_clean["amount_missing"] = (
    payments_clean["amount_numeric"].isna()
)

print(
    "Missing or invalid amounts:",
    payments_clean["amount_missing"].sum()
)

Missing or invalid amounts: 78

In [85]:
payments_analytics = payments_clean[
    [
        "payment_id",
        "booking_id",
        "amount_numeric",
        "payment_method"
    ]
].copy()

print(payments_analytics.shape)
print(payments_analytics.head())

(1000, 4)
  payment_id booking_id  amount_numeric payment_method
0    PAY1000      B1116         9883.49     NETBANKING
1    PAY1001      B1738         8457.96     NETBANKING
2    PAY1002      B1873         6495.37            UPI
3    PAY1003      B1914         5079.38     NETBANKING
4    PAY1004      B1967        12518.31           CARD

In [86]:
booking_flight_check = bookings_analytics[
    ~bookings_analytics["flight_id"].isin(
        flights_final["flight_id"]
    )
]

print("Bookings with missing flight IDs:", len(booking_flight_check))

Bookings with missing flight IDs: 0

In [87]:
booking_passenger_check = bookings_analytics[
    ~bookings_analytics["passenger_id"].isin(
        passengers_analytics["passenger_id"]
    )
]

print(
    "Bookings with missing passenger IDs:",
    len(booking_passenger_check)
)

Bookings with missing passenger IDs: 0

In [88]:
payment_booking_check = payments_analytics[
    ~payments_analytics["booking_id"].isin(
        bookings_analytics["booking_id"]
    )
]

print(
    "Payments with missing booking IDs:",
    len(payment_booking_check)
)

Payments with missing booking IDs: 0

In [89]:
import os

output_path = "../output"

os.makedirs(output_path, exist_ok=True)

print("Output folder ready:", output_path)

Output folder ready: ../output

In [90]:
flights_final.to_csv(
    "../output/flights_clean.csv",
    index=False
)

print("Flights dataset saved successfully.")

Flights dataset saved successfully.

In [91]:
bookings_analytics.to_csv(
    "../output/bookings_clean.csv",
    index=False
)

print("Bookings dataset saved successfully.")

Bookings dataset saved successfully.

In [92]:
passengers_analytics.to_csv(
    "../output/passengers_clean.csv",
    index=False
)

print("Passengers dataset saved successfully.")

Passengers dataset saved successfully.

In [93]:
payments_analytics.to_csv(
    "../output/payments_clean.csv",
    index=False
)

print("Payments dataset saved successfully.")

Payments dataset saved successfully.

In [94]:
data_quality_summary = pd.DataFrame({
    "Dataset": [
        "Flights",
        "Bookings",
        "Passengers",
        "Payments"
    ],
    "Original Rows": [
        len(flights),
        len(bookings),
        len(passengers),
        len(payments)
    ],
    "Final Rows": [
        len(flights_final),
        len(bookings_analytics),
        len(passengers_analytics),
        len(payments_analytics)
    ]
})

print(data_quality_summary)

      Dataset  Original Rows  Final Rows
0     Flights           1020        1005
1    Bookings           1000        1000
2  Passengers           1039        1039
3    Payments           1000        1000

In [95]:
cleaning_rules = pd.DataFrame({
    "Dataset": [
        "Flights",
        "Bookings",
        "Passengers",
        "Payments"
    ],
    "Cleaning / Transformation": [
        "Removed exact duplicates; standardized airline; calculated duration; identified overnight flights and time anomalies; created route",
        "Standardized missing and INVALID status values as Unknown",
        "Identified missing last names using a data-quality flag",
        "Converted payment amount to numeric; invalid and missing amounts treated as unknown"
    ]
})

print(cleaning_rules)

      Dataset                          Cleaning / Transformation
0     Flights  Removed exact duplicates; standardized airline...
1    Bookings  Standardized missing and INVALID status values...
2  Passengers  Identified missing last names using a data-qua...
3    Payments  Converted payment amount to numeric; invalid a...

In [96]:
kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Flights",
        "Average Flight Duration (minutes)",
        "Overnight Flights",
        "Time Anomalies",
        "Unique Routes"
    ],
    "Value": [
        len(flights_final),
        round(flights_final["duration_minutes"].mean(), 2),
        flights_final["overnight_flight"].sum(),
        flights_final["time_anomaly"].sum(),
        flights_final["route"].nunique()
    ]
})

print(kpi_summary)

                                 KPI    Value
0                      Total Flights  1005.00
1  Average Flight Duration (minutes)   164.62
2                  Overnight Flights   122.00
3                     Time Anomalies     1.00
4                      Unique Routes    30.00

In [97]:
route_traffic = (
    flights_final["route"]
    .value_counts()
    .reset_index()
)

route_traffic.columns = ["route", "flight_count"]

print(route_traffic.head(10))

       route  flight_count
0  BOM → CCU            90
1  CCU → DEL            72
2  MAA → BLR            65
3  BLR → BOM            60
4  HYD → MAA            57
5  DEL → HYD            54
6  HYD → DEL            42
7  BOM → DEL            39
8  CCU → BOM            33
9  DEL → BLR            29

In [98]:
airline_distribution = (
    flights_final["airline_standard"]
    .value_counts()
    .reset_index()
)

airline_distribution.columns = ["airline", "flight_count"]

print(airline_distribution)

     airline  flight_count
0     IndiGo           249
1   SpiceJet           236
2  Air India           233
3    Vistara           218
4    Unknown            69

In [99]:
airline_duration = (
    flights_final
    .groupby("airline_standard")["duration_minutes"]
    .mean()
    .round(2)
    .reset_index()
)

airline_duration.columns = [
    "airline",
    "average_duration_minutes"
]

print(airline_duration)

     airline  average_duration_minutes
0  Air India                    163.15
1     IndiGo                    167.70
2   SpiceJet                    164.19
3    Unknown                    166.07
4    Vistara                    162.68

In [100]:
anomaly_summary = pd.DataFrame({
    "Metric": [
        "Total Flights",
        "Time Anomalies",
        "Anomaly Percentage"
    ],
    "Value": [
        len(flights_final),
        flights_final["time_anomaly"].sum(),
        round(
            flights_final["time_anomaly"].mean() * 100,
            2
        )
    ]
})

print(anomaly_summary)

               Metric   Value
0       Total Flights  1005.0
1      Time Anomalies     1.0
2  Anomaly Percentage     0.1

In [101]:
kpi_summary.to_csv(
    "../output/kpi_summary.csv",
    index=False
)

print("KPI summary saved successfully.")

KPI summary saved successfully.

In [102]:
route_traffic.to_csv(
    "../output/route_traffic.csv",
    index=False
)

print("Route traffic saved successfully.")

Route traffic saved successfully.

In [103]:
airline_distribution.to_csv(
    "../output/airline_distribution.csv",
    index=False
)

print("Airline distribution saved successfully.")

Airline distribution saved successfully.

In [104]:
airline_duration.to_csv(
    "../output/airline_duration.csv",
    index=False
)

print("Airline duration saved successfully.")

Airline duration saved successfully.

In [105]:
import os

print(os.listdir("../output"))

['airline_distribution.csv', 'airline_duration.csv', 'bookings_clean.csv', 'flights_clean.csv', 'kpi_summary.csv', 'passengers_clean.csv', 'payments_clean.csv', 'route_traffic.csv']

In [106]:
bookings_analytics[
    bookings_analytics["flight_id"] == "6F250"
]

,booking_id,passenger_id,flight_id,booking_date,status_standard,seat_number
235,B1235,P1979,6F250,2025-12-23 11:37:36.951,PENDING,13D
294,B1294,P1898,6F250,2025-07-13 11:37:36.951,CANCELLED,34B

In [107]:
flights_clean[
    flights_clean["flight_id"] == "6F250"
]

,flight_id,airline,source,destination,departure_time,arrival_time,duration,calculated_duration,duration_timedelta,time_anomaly,duplicate_flight_id,airline_missing,airline_standard,duration_minutes,overnight_flight,route
253,6F250,UNKNOWN,DEL,BLR,2026-04-20 03:26:41.701,2026-04-20 07:30:41.701,04:04:00,0 days 04:04:00,0 days 04:04:00,False,True,False,Unknown,244.0,False,DEL → BLR
270,6F250,UNKNOWN,CCU,BLR,2026-04-20 02:23:41.702,2026-04-20 02:56:41.702,00:33:00,0 days 00:33:00,0 days 00:33:00,False,True,False,Unknown,33.0,False,CCU → BLR

In [108]:
flights_final["flight_id_conflict"] = (
    flights_final["flight_id"] == "6F250"
)

print(
    "Conflicting flight records:",
    flights_final["flight_id_conflict"].sum()
)

Conflicting flight records: 2

In [109]:
flights_final["flight_key"] = (
    flights_final.index + 1
).astype(str).map(lambda x: "FL" + x.zfill(4))

print(flights_final[["flight_id", "flight_key"]].head())

  flight_id flight_key
0     SJ010     FL0001
1     AI155     FL0002
2     UK094     FL0003
3     AI245     FL0004
4     AI192     FL0005

In [110]:
print("Flight records:", len(flights_final))
print("Unique flight IDs:", flights_final["flight_id"].nunique())
print("Duplicate flight IDs:",
      flights_final["flight_id"].duplicated().sum())

Flight records: 1005
Unique flight IDs: 1004
Duplicate flight IDs: 1

In [111]:
flight_id_reference = (
    flights_final
    .groupby("flight_id")
    .agg(
        flight_record_count=("flight_key", "count")
    )
    .reset_index()
)

flight_id_reference["flight_id_conflict"] = (
    flight_id_reference["flight_record_count"] > 1
)

print(flight_id_reference.head())
print(
    "Conflicting flight IDs:",
    flight_id_reference["flight_id_conflict"].sum()
)

  flight_id  flight_record_count  flight_id_conflict
0     6F001                    1               False
1     6F002                    1               False
2     6F003                    1               False
3     6F004                    1               False
4     6F005                    1               False
Conflicting flight IDs: 1

In [112]:
flight_id_reference.to_csv(
    "../output/flight_id_reference.csv",
    index=False
)

print("Flight ID reference saved successfully.")

Flight ID reference saved successfully.

In [113]:
flights_final.to_csv(
    "../output/flights_clean.csv",
    index=False
)

print("Updated Flights dataset saved successfully.")

Updated Flights dataset saved successfully.

In [114]:
print("Passenger records:", len(passengers_analytics))
print("Unique passenger IDs:", passengers_analytics["passenger_id"].nunique())
print(
    "Duplicate passenger IDs:",
    passengers_analytics["passenger_id"].duplicated().sum()
)

Passenger records: 1039
Unique passenger IDs: 1000
Duplicate passenger IDs: 39

In [115]:
passenger_duplicate_rows = passengers_analytics[
    passengers_analytics["passenger_id"].duplicated(keep=False)
]

print(
    "Duplicate passenger ID records:",
    len(passenger_duplicate_rows)
)

print(
    "Exact duplicate rows:",
    passenger_duplicate_rows.duplicated().sum()
)

Duplicate passenger ID records: 75
Exact duplicate rows: 0

In [116]:
passenger_duplicate_rows.sort_values("passenger_id").head(20)

    passenger_id      first_name last_name  age gender date_of_birth
34         P1034          Ishaan      Iyer   62      M    1964-08-14
35         P1034          Ishaan      Iyer   62      M    1964-09-24
103        P1102            Myra  Kulkarni    1      F    2025-02-27
104        P1102            Myra  Kulkarni    1      F    2025-03-18
106        P1104          Vivaan     Verma   88      F    1938-06-03
107        P1104          Vivaan     Verma   88      F    1938-12-25
108        P1104          Vivaan     Verma   88      F    1938-04-02
113        P1108  IshaanKulkarni       NaN    8      M    2018-06-13
112        P1108          Ishaan  Kulkarni    8      M    2018-02-08
145        P1140         Shaurya     Singh   42      M    1984-08-02
146        P1140         Shaurya     Singh   42      M    1984-03-18
147        P1141             Sai  Kulkarni   77      M    1949-06-05
148        P1141     SaiKulkarni       NaN   77      M    1949-10-22
185        P1178           Kavya     Naidu   72      M    1954-02-15
186        P1178      Kavyanaidu       NaN   72      M    1954-09-09
225        P1216            Riya    Sharma   56      F    1970-02-11
224        P1216            Riya    Sharma   56      F    1970-07-12
246        P1236      MyraSharma       NaN   20      F    2006-01-28
245        P1236            Myra    Sharma   20      F    2006-03-22
262        P1252          Aadhya   Agarwal   16      M    2010-04-11

In [117]:
passenger_id_reference = (
    passengers_analytics
    .groupby("passenger_id")
    .agg(
        passenger_record_count=("passenger_id", "count")
    )
    .reset_index()
)

passenger_id_reference["passenger_id_conflict"] = (
    passenger_id_reference["passenger_record_count"] > 1
)

print(passenger_id_reference.head())
print(
    "Conflicting passenger IDs:",
    passenger_id_reference["passenger_id_conflict"].sum()
)

  passenger_id  passenger_record_count  passenger_id_conflict
0        P1000                       1                  False
1        P1001                       1                  False
2        P1002                       1                  False
3        P1003                       1                  False
4        P1004                       1                  False
Conflicting passenger IDs: 36

In [118]:
passenger_id_reference.to_csv(
    "../output/passenger_id_reference.csv",
    index=False
)

print("Passenger ID reference saved successfully.")

Passenger ID reference saved successfully.